---
# deploy java project
- hosts: "{{idc}}"
  pre_tasks:
    - include: roles/common/tasks/main.yml

  roles:
    - "{{project}}"

  post_tasks:
      - include: roles/common/tasks/nginx_action.yml

- name: write the nginx config
  template: src={{item}} dest=/opt/soft/nginx/conf/{{item}}
  with_items:
    - "{{files_all if 'all'== file_name else file_name}}"
  when: file_name == 'all' or file_name in files_all